"""Export pump / system data as EPANET 2.2 input-file text.

Produces ``[CURVES]`` (PUMP + EFFICIENCY), ``[PUMPS]`` and ``[ENERGY]`` blocks
in a chosen flow unit, and can splice them into an existing ``.inp`` file.

Head is always in metres (EPANET SI flow units: LPS, LPM, MLD, CMH, CMD).
US flow units are converted but head stays metric - convert to feet yourself
if your model is in US units.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .pumpcurve import PumpCurve
from .system import SystemCurve

# flow unit -> multiplier applied to Q in m3/s
FLOW_UNITS = {
    "LPS": 1_000.0,
    "LPM": 60_000.0,
    "MLD": 86.4,
    "CMH": 3_600.0,
    "CMD": 86_400.0,
    "GPM": 15_850.323,
    "MGD": 22.824465,
    "CFS": 35.314667,
}
SI_FLOW_UNITS = {"LPS", "LPM", "MLD", "CMH", "CMD"}


def _fmt(x: float, nd: int = 5) -> str:
    if abs(x) < 1e-9:
        return "0"
    return f"{round(x, 6):.{nd}g}"


def pump_curve_points(
    pump: PumpCurve, *, n_points: int = 3, flow_units: str = "LPS", q_max_m3s: float | None = None
) -> list[tuple[float, float]]:
    """(flow, head) points in ``flow_units`` / m.  ``n_points=3`` emits
    shut-off, design/BEP and runout so EPANET refits the same A-B*Q^C law;
    a larger value emits a multi-point curve EPANET uses piecewise-linearly."""
    mult = FLOW_UNITS[flow_units.upper()]
    q_max = q_max_m3s if q_max_m3s is not None else pump.max_flow()
    if n_points <= 1:
        qb, hb, _ = pump.bep()
        return [(qb * mult, hb)]
    if n_points == 3:
        qb, _, _ = pump.bep()
        qs = np.array([0.0, qb, min(q_max, pump.max_flow())])
    else:
        qs = np.linspace(0.0, q_max, n_points)
    hs = pump.head(qs)
    pts = [(float(q * mult), float(max(h, 0.0))) for q, h in zip(qs, hs)]
    # EPANET rejects duplicate/non-increasing flows and a leading 0,0
    cleaned: list[tuple[float, float]] = []
    for q, h in pts:
        if cleaned and q <= cleaned[-1][0] + 1e-9:
            continue
        cleaned.append((q, h))
    return cleaned


def efficiency_curve_points(
    pump: PumpCurve, *, n_points: int = 7, flow_units: str = "LPS", floor_pct: float = 5.0
) -> list[tuple[float, float]]:
    """Efficiency (Q vs %) sampled across ~40-120% of BEP flow - the range an
    EPANET energy analysis actually needs.  Values are floored at ``floor_pct``
    so the curve stays usable at the extremes."""
    if pump.eff_pts is None:
        return []
    mult = FLOW_UNITS[flow_units.upper()]
    q_bep, _, _ = pump.bep()
    q_lo = max(0.40 * q_bep, pump.eff_q_pts[0] * pump._scale_q, 1e-6)
    q_hi = min(1.20 * q_bep, pump.eff_q_pts[-1] * pump._scale_q)
    qs = np.linspace(q_lo, q_hi, n_points)
    return [(float(q * mult), round(float(max(pump.efficiency(q), floor_pct)), 2)) for q in qs]


@dataclass
class EpanetPumpExport:
    pump_id: str
    from_node: str
    to_node: str
    head_curve_id: str
    efficiency_curve_id: str | None
    flow_units: str
    head_points: list[tuple[float, float]]
    efficiency_points: list[tuple[float, float]]
    speed: float = 1.0
    speed_pattern: str | None = None
    price_per_kwh: float | None = None
    price_pattern: str | None = None

    # -- section text -------------------------------------------------
    def curves_section(self) -> str:
        lines = [
            ";; generated by pumpsizer",
            f";; flow units: {self.flow_units}   head: m",
            "[CURVES]",
            ";ID              X-Value     Y-Value",
        ]
        lines.append(f";  {self.head_curve_id}: pump head curve (Q vs H)")
        for q, h in self.head_points:
            lines.append(f" {self.head_curve_id:<15} {_fmt(q):>11} {_fmt(h):>11}")
        if self.efficiency_points and self.efficiency_curve_id:
            lines.append(f";  {self.efficiency_curve_id}: wire-to-water / pump efficiency (Q vs %)")
            for q, e in self.efficiency_points:
                lines.append(f" {self.efficiency_curve_id:<15} {_fmt(q):>11} {_fmt(e):>11}")
        return "\n".join(lines)

    def pumps_section(self) -> str:
        parts = [
            f" {self.pump_id:<15} {self.from_node:<10} {self.to_node:<10}",
            f"HEAD {self.head_curve_id}",
        ]
        if self.speed and abs(self.speed - 1.0) > 1e-6:
            parts.append(f"SPEED {_fmt(self.speed)}")
        if self.speed_pattern:
            parts.append(f"PATTERN {self.speed_pattern}")
        return "[PUMPS]\n;ID              Node1      Node2      Parameters\n" + "  ".join(parts)

    def energy_section(self) -> str:
        if not (self.efficiency_curve_id or self.price_per_kwh):
            return ""
        lines = ["[ENERGY]"]
        if self.efficiency_curve_id:
            lines.append(f" PUMP {self.pump_id}   EFFIC   {self.efficiency_curve_id}")
        if self.price_per_kwh is not None:
            lines.append(f" PUMP {self.pump_id}   PRICE   {_fmt(self.price_per_kwh)}")
        if self.price_pattern:
            lines.append(f" PUMP {self.pump_id}   PATTERN {self.price_pattern}")
        return "\n".join(lines)

    def full_snippet(self) -> str:
        blocks = [self.curves_section(), "", self.pumps_section()]
        es = self.energy_section()
        if es:
            blocks += ["", es]
        return "\n".join(blocks) + "\n"


def build_pump_export(
    pump: PumpCurve,
    *,
    pump_id: str = "PMP1",
    from_node: str = "SUC",
    to_node: str = "DIS",
    curve_id: str | None = None,
    flow_units: str = "LPS",
    head_points: int = 3,
    efficiency_points: int = 7,
    speed: float = 1.0,
    speed_pattern: str | None = None,
    price_per_kwh: float | None = None,
    price_pattern: str | None = None,
) -> EpanetPumpExport:
    fu = flow_units.upper()
    if fu not in FLOW_UNITS:
        raise ValueError(f"unknown EPANET flow unit {flow_units!r}; pick from {sorted(FLOW_UNITS)}")
    cid = curve_id or f"C_{pump_id}"
    hp = pump_curve_points(pump, n_points=head_points, flow_units=fu)
    ep = efficiency_curve_points(pump, n_points=efficiency_points, flow_units=fu)
    return EpanetPumpExport(
        pump_id=pump_id,
        from_node=from_node,
        to_node=to_node,
        head_curve_id=cid,
        efficiency_curve_id=(f"E_{pump_id}" if ep else None),
        flow_units=fu,
        head_points=hp,
        efficiency_points=ep,
        speed=speed,
        speed_pattern=speed_pattern,
        price_per_kwh=price_per_kwh,
        price_pattern=price_pattern,
    )


def system_curve_points(
    system: SystemCurve, q_max_m3s: float, *, n: int = 20, flow_units: str = "LPS"
) -> list[tuple[float, float]]:
    """System curve as (flow, head) - handy as an EPANET GPV/analysis reference."""
    mult = FLOW_UNITS[flow_units.upper()]
    q, h = system.sample(q_max_m3s, n)
    return [(float(qi * mult), float(hi)) for qi, hi in zip(q, h)]


# ----------------------------------------------------------------------
# splice into an existing .inp  (Phase 3 groundwork - simple + explicit)
# ----------------------------------------------------------------------
_SECTION_RE = re.compile(r"^\s*\[([A-Z_]+)\]", re.IGNORECASE)


def read_sections(text: str) -> dict[str, list[str]]:
    """Split an .inp into ``{SECTION: [lines...]}`` preserving order via dict."""
    sections: dict[str, list[str]] = {}
    current = "_PREAMBLE"
    sections[current] = []
    for line in text.splitlines():
        m = _SECTION_RE.match(line)
        if m:
            current = m.group(1).upper()
            sections.setdefault(current, [])
            continue
        sections.setdefault(current, []).append(line)
    return sections


def patch_inp(
    inp_path: str | Path,
    export: EpanetPumpExport,
    *,
    output_path: str | Path | None = None,
    replace_pump: bool = True,
) -> str:
    """Splice this pump's head curve, efficiency curve, ``[PUMPS]`` line and
    ``[ENERGY]`` entries into an existing ``.inp`` (via :class:`InpModel`, which
    preserves section order and every other section verbatim).  Returns the new
    file text and writes it when ``output_path`` is given.

    ``replace_pump=False`` keeps any existing ``[PUMPS]`` line for the same id
    (a new one is still appended - EPANET would reject the duplicate, so this is
    only for diffing)."""
    from .inpfile import InpModel

    model = InpModel.read(inp_path)
    if not replace_pump:
        model._ensure("PUMPS")
        existing = list(model.sections["PUMPS"])
        model.apply_export(export)
        model.sections["PUMPS"] = existing + [
            ln for ln in model.sections["PUMPS"] if ln not in existing
        ]
    else:
        model.apply_export(export)
    text = model.to_text()
    if output_path is not None:
        Path(output_path).write_text(text)
    return text
