"""Regenerate src/pumpsizer/data/catalog/ksb_omega_50hz.yaml from the KSB
'Omega / Omega V 50 Hz Characteristic Curves Booklet' PDF.

    py tools/build_ksb_omega_catalog.py path/to/dow-omega-data.pdf

Only axis ranges, page numbers, speeds and impeller-diameter labels are
extractable from that PDF; BEP is approximated (see docs/catalog_from_ksb.md).
Needs pypdf + pyyaml.
"""
from __future__ import annotations

import io
import re
import sys
from pathlib import Path

import yaml
from pypdf import PdfReader

OUT = Path(__file__).resolve().parents[1] / "src/pumpsizer/data/catalog/ksb_omega_50hz.yaml"


def parse(pdf_path: str) -> list[dict]:
    r = PdfReader(pdf_path)
    raw: dict[tuple[str, int], dict] = {}
    for i, pg in enumerate(r.pages):
        t = pg.extract_text() or ""
        m = re.search(r"Omega\s+(\d{3}-\d{3}[A-C]),\s*n\s*=\s*(\d+)\s*rpm", t)
        if not m:
            continue
        size, rpm = m.group(1), int(m.group(2))
        qh = re.search(r"([\d\s]+?)Q\s*\[m³/h\]", t)
        hm = re.search(r"Q\s*\[IM\.gpm\]\s*([\d\s.]+?)H\s*\[m\]", t)
        raw[(size, rpm)] = {
            "page": i + 1,
            "q_m3h_max": max((float(x) for x in qh.group(1).split()), default=None) if qh else None,
            "h_m_max": max((float(x) for x in hm.group(1).split()), default=None) if hm else None,
            "impellers": sorted({int(x) for x in re.findall(r"ø\s?(\d{2,3})", t)}, reverse=True),
        }

    def sib(size, rpm, field):
        for v in "ABC":
            d = raw.get((size[:-1] + v, rpm))
            if d and d[field]:
                return d[field]
        return None

    pumps = []
    for (size, rpm), d in sorted(raw.items(), key=lambda kv: (kv[0][1], kv[0][0])):
        q_m3h = d["q_m3h_max"] or sib(size, rpm, "q_m3h_max")
        h0 = d["h_m_max"] or sib(size, rpm, "h_m_max")
        imp = d["impellers"] or sib(size, rpm, "impellers") or []
        if not (q_m3h and h0):
            continue
        q_max = round(q_m3h / 3.6, 1)
        pumps.append({
            "manufacturer": "KSB", "series": "Omega", "model": f"{size} ({rpm}rpm)",
            "reference_speed_rpm": rpm, "poles": 2 if rpm > 2000 else 4,
            "discharge_dn": int(size.split("-")[0]),
            "impeller_diameter_mm": max(imp) if imp else None,
            "min_impeller_diameter_mm": min(imp) if imp else None,
            "impeller_options_mm": imp or None,
            "envelope_only": True, "estimated_bep": True, "verified": False,
            "q_bep_lps": round(0.60 * q_max, 1), "h_bep_m": round(0.72 * h0, 1),
            "q_min_lps": round(0.30 * q_max, 1), "q_max_lps": q_max,
            "shutoff_head_m": h0, "datasheet_page": d["page"],
            "source": "KSB Omega / Omega V 50 Hz Characteristic Curves Booklet (15.02.2016)",
            "notes": "envelope from datasheet axis ranges; BEP approximated "
                     "(q_bep~0.6*q_max, h_bep~0.72*h_shutoff) - confirm from the curve page",
        })
    return pumps


def main() -> None:
    pdf = sys.argv[1] if len(sys.argv) > 1 else "KSB/dow-omega-data.pdf"
    pumps = parse(pdf)
    hdr = (
        "# KSB Omega / Omega V, 50 Hz - axially split volute casing pumps for water supply.\n"
        "# Envelope-only entries: Q/H bounds read from each datasheet page's axis ranges;\n"
        "# BEP is APPROXIMATED and every entry is verified: false + estimated_bep: true.\n"
        "# Upgrade an entry with a real `curve:` block per docs/catalog_from_ksb.md.\n"
        f"# Generated by tools/build_ksb_omega_catalog.py : {len(pumps)} sizes.\n\n"
    )
    with io.open(OUT, "w", encoding="utf-8") as fh:
        fh.write(hdr)
        fh.write(yaml.safe_dump({"pumps": pumps}, sort_keys=False, allow_unicode=True))
    print(f"wrote {len(pumps)} sizes -> {OUT}")


if __name__ == "__main__":
    main()
